(function(){
const ROOT='https://sites84.github.io/Tudo-sobre-o-crime/';
const API='https://api.github.com/repos/sites84/Tudo-sobre-o-crime/';
function E(id){return document.getElementById(id)}
function absAsset(src){if(!src)return '';src=String(src).replace(/^\.\.\//,'').replace(/^\//,'');if(/^https?:\/\//i.test(src))return src;return ROOT+src}
function normalizeImages(root){root.querySelectorAll('img').forEach(img=>{const s=img.getAttribute('src')||'';if(s)img.src=absAsset(s);img.style.maxWidth='100%';img.style.height='auto'})}
async function dynamicFiles(html){const doc=new DOMParser().parseFromString(html,'text/html');const sc=[...doc.querySelectorAll('script')].find(s=>/const\s+files\s*=/.test(s.textContent||''));if(!sc)return[];const m=(sc.textContent||'').match(/const\s+files\s*=\s*\[([\s\S]*?)\]/);if(!m)return[];const names=[...m[1].matchAll(/["']([^"']+\.htmlfrag)["']/g)].map(x=>x[1]);const out=[];for(const n of names){try{const base=html.includes('/casos/')?'casos/':'';const d=await gh(base+n);out.push({path:base+n,sha:d.sha,html:dec(d.content)})}catch(e){}}return out}
window.editCase=async function(path){try{const d=await gh(path),html=dec(d.content),doc=new DOMParser().parseFromString(html,'text/html');const root=doc.querySelector('article')||doc.querySelector('main')||doc.body;const dyn=await dynamicFiles(html);if(dyn.length)root.innerHTML=dyn.map(x=>x.html).join('\n');normalizeImages(root);TSC.current={path,sha:d.sha,html:doc.documentElement.outerHTML,dynamicFiles:dyn};E('path').value=path;E('slug').value=path.split('/').pop().replace(/\.html$/,'');E('slug').dataset.edited='1';E('title').value=doc.querySelector('title')?.textContent||root.querySelector('h1')?.textContent||'';E('desc').value=doc.querySelector('meta[name="description"]')?.content||'';E('coverPath').value=assetPath(doc.querySelector('meta[property="og:image"]')?.content||'');E('area').innerHTML=root.innerHTML;normalizeImages(E('area'));E('editorHeading').textContent='Editando: '+path;E('editorStatus').textContent='Conteúdo carregado diretamente do HTML do GitHub.';const b=document.querySelector('#editor .primary');if(b){b.textContent='Salvar no GitHub';b.onclick=savePost}show('editor')}catch(e){notify(e.message,false)}};
window.savePost=async function(){if(!TSC.current)return notify('Nenhum post carregado.',false);try{const newPath='casos/'+slug(E('slug').value)+'.html';if(newPath!==TSC.current.path)return renameAndSave(newPath);const fresh=await gh(TSC.current.path),doc=new DOMParser().parseFromString(dec(fresh.content),'text/html');doc.title=E('title').value.trim();let m=doc.querySelector('meta[name="description"]');if(!m){m=doc.createElement('meta');m.name='description';doc.head.appendChild(m)}m.content=E('desc').value.trim();const root=doc.querySelector('article')||doc.querySelector('main')||doc.body;root.innerHTML=E('area').innerHTML;normalizeImages(root);const out='<!doctype html>\n'+doc.documentElement.outerHTML;const j=await put(TSC.current.path,out,'Atualiza post pelo editor visual',fresh.sha);TSC.current.sha=j.content.sha;TSC.current.html=out;notify('Post salvo no GitHub.')}catch(e){notify(e.message,false)}};
function chooseImage(cb){const i=document.createElement('input');i.type='file';i.accept='image/png,image/jpeg,image/webp,image/jpg';i.onchange=()=>{const f=i.files?.[0];if(f)cb(f)};i.click()}
function convertUpload(file,name){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));fr.onload=()=>{const im=new Image();im.onerror=()=>reject(new Error('Não foi possível processar a imagem.'));im.onload=async()=>{try{const max=2400,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);const data=c.toDataURL('image/webp',.88).split(',')[1],p='assets/'+slug(name)+'.webp';let old=null;try{old=await gh(p)}catch(e){}await put(p,data,'Adiciona imagem pelo editor visual',old&&old.sha);resolve({path:p,url:absAsset(p)})}catch(e){reject(e)}};im.src=fr.result};fr.readAsDataURL(file)})}
window.insertImage=async function(){chooseImage(async f=>{const n=prompt('Nome da imagem:',f.name.replace(/\.[^.]+$/,''));if(!n)return;try{const r=await convertUpload(f,n),ed=E('area');ed.focus(),sel=getSelection();let range;if(sel.rangeCount&&ed.contains(sel.anchorNode))range=sel.getRangeAt(0);else{range=document.createRange();range.selectNodeContents(ed);range.collapse(false)}const img=document.createElement('img');img.src=r.url;img.alt=n;img.style.maxWidth='100%';img.style.height='auto';range.deleteContents();range.insertNode(img);range.setStartAfter(img);range.collapse(true);sel.removeAllRanges();sel.addRange(range);notify('Imagem enviada e inserida no ponto do cursor.')}catch(e){notify(e.message,false)}})};
window.uploadCover=async function(){chooseImage(async f=>{const n=prompt('Nome da capa:',(E('title').value||f.name).replace(/\.[^.]+$/,''));if(!n)return;try{const r=await convertUpload(f,n);E('coverPath').value=r.path;notify('Capa enviada. Clique em Salvar capa.')}catch(e){notify(e.message,false)}})};
window.saveCover=async function(){if(!TSC.current)return notify('Abra um post primeiro.',false);const p=E('coverPath').value.trim();if(!p)return notify('Envie uma capa primeiro.',false);try{const fresh=await gh(TSC.current.path),doc=new DOMParser().parseFromString(dec(fresh.content),'text/html');let m=doc.querySelector('meta[property="og:image"]');if(!m){m=doc.createElement('meta');m.setAttribute('property','og:image');doc.head.appendChild(m)}m.content=absAsset(p);const root=doc.querySelector('article')||doc.querySelector('main')||doc.body;let cover=root.querySelector('.post-cover');if(!cover){cover=doc.createElement('figure');cover.className='post-cover';root.insertBefore(cover,root.firstChild)}cover.innerHTML='<img src="'+absAsset(p)+'" alt="Capa do caso">';const out='<!doctype html>\n'+doc.documentElement.outerHTML,j=await put(TSC.current.path,out,'Define capa do post',fresh.sha);TSC.current.sha=j.content.sha;TSC.current.html=out;if(typeof updateHomeCover==='function')await updateHomeCover(TSC.current.path,p);notify('Capa salva corretamente.')}catch(e){notify(e.message,false)}};
window.render=async function(){try{const list=await gh('casos'),files=(list||[]).filter(x=>x.type==='file'&&/\.html$/i.test(x.name)),rows=[];for(const f of files){try{const d=await gh(f.path),doc=new DOMParser().parseFromString(dec(d.content),'text/html');const title=doc.querySelector('title')?.textContent||doc.querySelector('h1')?.textContent||f.name.replace(/\.html$/,'');const desc=doc.querySelector('meta[name="description"]')?.content||'Leia a reconstrução completa do caso.';const cover=doc.querySelector('meta[property="og:image"]')?.content||'';let date='';try{const r=await fetch(API+'commits?path='+encodeURIComponent(f.path)+'&per_page=1',{headers:ghHeaders()});if(r.ok){const a=await r.json();date=a[0]?.commit?.author?.date||''}}catch(e){}rows.push({path:f.path,title,desc,cover,date})}catch(e){}}rows.sort((a,b)=>String(b.date).localeCompare(String(a.date)));const html=rows.map(c=>'<article class="case"><div class="cover">'+(c.cover?'<img src="'+absAsset(c.cover)+'" alt="Capa">':'')+'</div><div class="case-body"><div class="tag">Publicado</div><h2>'+esc(c.title)+'</h2><p>'+esc(c.path)+'</p><div class="actions"><button class="btn primary" onclick="editCase(\''+c.path+'\')">Editar</button><button class="btn" onclick="window.open(\'../'+c.path+'\',\'_blank\')">Ver ↗</button></div></div></article>').join('')||'<p class="status">Nenhum caso encontrado.</p>';if(E('caseGrid'))E('caseGrid').innerHTML=html;if(E('caseGrid2'))E('caseGrid2').innerHTML=html}catch(e){notify('Erro ao carregar casos: '+e.message,false)}};
setTimeout(()=>window.render(),150);
})();