const TSC={owner:'sites84',repo:'Tudo-sobre-o-crime',branch:'main',current:null};
const $e=id=>document.getElementById(id);
function ghHeaders(){const t=localStorage.getItem('tsc_github_token')||'';if(!t)throw Error('Configure o token GitHub em Configurações.');return {'Accept':'application/vnd.github+json','Authorization':'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'}}
async function gh(path,opts={}){const r=await fetch(`https://api.github.com/repos/${TSC.owner}/${TSC.repo}/contents/${path}?ref=${TSC.branch}`,{...opts,headers:{...ghHeaders(),...(opts.headers||{})}});if(!r.ok){let j={};try{j=await r.json()}catch{}throw Error(j.message||r.statusText)}return r.json()}
function toast2(msg,ok=true){if(typeof notify==='function')notify(msg,ok);else alert(msg)}
function decodeGitHub(s){const bin=atob(s.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encodeUtf8(s){return btoa(unescape(encodeURIComponent(s)))}
async function editCase(path){try{const d=await gh(path);const html=decodeGitHub(d.content);const doc=new DOMParser().parseFromString(html,'text/html');TSC.current={path,sha:d.sha,html};$e('path').value=path;$e('title').value=doc.querySelector('title')?.textContent||doc.querySelector('h1')?.textContent||'';$e('desc').value=doc.querySelector('meta[name="description"]')?.content||'';const root=doc.querySelector('article')||doc.querySelector('main')||doc.body;let content=root.innerHTML;if(root===doc.body){const header=doc.querySelector('header');const footer=doc.querySelector('footer');if(header)content=content.replace(header.outerHTML,'');if(footer)content=content.replace(footer.outerHTML,'')} $e('area').innerHTML=content;$e('editorHeading').textContent='Editando: '+path;$e('editorStatus').textContent='Conteúdo real carregado do GitHub.';show('editor')}catch(e){toast2(e.message,false)}}
async function savePost(){if(!TSC.current)return toast2('Nenhum post carregado.',false);try{const doc=new DOMParser().parseFromString(TSC.current.html,'text/html');doc.title=$e('title').value.trim();let meta=doc.querySelector('meta[name="description"]');if(!meta){meta=doc.createElement('meta');meta.name='description';doc.head.appendChild(meta)}meta.content=$e('desc').value.trim();const root=doc.querySelector('article')||doc.querySelector('main')||doc.body;root.innerHTML=$e('area').innerHTML;const out='<!doctype html>\n'+doc.documentElement.outerHTML;const r=await fetch(`https://api.github.com/repos/${TSC.owner}/${TSC.repo}/contents/${TSC.current.path}`,{method:'PUT',headers:{...ghHeaders(),'Content-Type':'application/json'},body:JSON.stringify({message:'Atualiza post pelo editor visual',content:encodeUtf8(out),sha:TSC.current.sha,branch:TSC.branch})});if(!r.ok){const j=await r.json();throw Error(j.message||r.statusText)}const j=await r.json();TSC.current.sha=j.content.sha;TSC.current.html=out;toast2('Post salvo no GitHub.')}catch(e){toast2(e.message,false)}}
function insertImage(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const f=input.files[0];if(!f)return;try{const name=prompt('Nome da imagem (sem extensão):',f.name.replace(/\.[^.]+$/,''));if(!name)return;const safe=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'.webp';const data=await toWebp(f);const path='assets/'+safe;let old=null;try{old=await gh(path)}catch{}const body={message:'Adiciona imagem pelo editor visual',content:data.split(',')[1],branch:TSC.branch};if(old)body.sha=old.sha;const r=await fetch(`https://api.github.com/repos/${TSC.owner}/${TSC.repo}/contents/${path}`,{method:'PUT',headers:{...ghHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const j=await r.json();throw Error(j.message||r.statusText)}document.execCommand('insertImage',false,'../assets/'+safe);toast2('Imagem enviada e inserida no ponto do cursor.')}catch(e){toast2(e.message,false)}};input.click()}
function toWebp(file){return new Promise((resolve,reject)=>{const fr=new FileReader(),im=new Image;fr.onload=()=>{im.onload=()=>{const max=2400,s=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.88))};im.onerror=reject;im.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
async function loadMedia(){try{const a=await gh('assets');const imgs=a.filter(x=>x.type==='file'&&/\.(webp|png|jpe?g)$/i.test(x.name));$e('mediaGrid').innerHTML=imgs.map(x=>`<div class="mediaItem"><img src="${x.download_url}"><div class="status">${x.name}</div><button class="btn" onclick="navigator.clipboard?.writeText('../assets/${x.name}');toast2('Caminho copiado.')">Copiar caminho</button></div>`).join('')}catch(e){$e('mediaGrid').innerHTML='<div class="status">'+e.message+'</div>'}}
function saveToken(){const v=$e('token').value.trim();if(!v)return toast2('Digite o token.',false);localStorage.setItem('tsc_github_token',v);$e('token').value='';toast2('Token salvo neste navegador.');render()}
function newCase(){TSC.current=null;$e('path').value='casos/novo-caso.html';$e('title').value='';$e('desc').value='';$e('area').innerHTML='<h1>Novo caso</h1><p>Comece a escrever a história aqui.</p>';$e('editorHeading').textContent='Novo caso';$e('editorStatus').textContent='Editor pronto. A criação de novos arquivos será ativada na próxima etapa.';show('editor')}
async function render(){const cards=[['Jeffrey Dahmer: o caso de Milwaukee','casos/jeffrey-dahmer.html','casos/capa-jeffrey-dahmer.webp'],['Ted Bundy: o caso','casos/ted-bundy.html','assets/ted-bundy-capa.webp'],['JonBenét Ramsey: o caso que continua aberto','casos/jonbenet-ramsey.html','assets/jonbenet-ramsey-capa.webp'],['O.J. Simpson: o caso','casos/o-j-simpson.html',null]];const html=cards.map(c=>`<article class="case"><div class="cover">${c[2]?`<img src="../${c[2]}">`:'<div style="margin:auto;color:#666">Sem capa</div>'}</div><div class="case-body"><div class="tag">Publicado</div><h2>${c[0]}</h2><p>${c[1]}</p><div class="actions"><button class="btn primary" onclick="editCase('${c[1]}')">Editar</button><button class="btn" onclick="window.open('../${c[1]}','_blank')">Ver ↗</button></div></div></article>`).join('');if($e('caseGrid'))$e('caseGrid').innerHTML=html;if($e('caseGrid2'))$e('caseGrid2').innerHTML=html}
window.editCase=editCase;window.savePost=savePost;window.insertImage=insertImage;window.loadMedia=loadMedia;window.saveToken=saveToken;window.newCase=newCase;window.render=render;
